-- PhraseAlias migration UP file


CREATE TABLE phrase_alias (id INT AUTO_INCREMENT NOT NULL, phrase_id INT DEFAULT NULL, help VARCHAR(255) DEFAULT NULL, oldId INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, INDEX IDX_2DEB233E8671F084 (phrase_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE phrase_alias ADD CONSTRAINT FK_2DEB233E8671F084 FOREIGN KEY (phrase_id) REFERENCES phrase (id) ON DELETE SET NULL;
