#!/bin/bash

if [ ! -d ./temp ]; then
    mkdir -m 777 ./temp
else
	chmod 777 ./temp
	rm -rf ./temp/*
fi

if [ ! -d ./temp/sessions ]; then
    mkdir -m 777 ./temp/sessions
else
	chmod 777 ./temp/sessions
fi

if [ ! -d ./log ]; then
    mkdir -m 777 ./log
else
	chmod 777 ./log
fi

if [ ! -d ./public/webtemp ]; then
    mkdir -m 777 ./public/webtemp
else
	chmod 777 ./public/webtemp
	rm -rf ./public/webtemp/*
fi

if [ ! -d ./app/locale ]; then
    mkdir -m 777 ./app/locale
else
	chmod -R 777 ./app/locale
fi

if [ ! -d ./public/storage ]; then
    mkdir -m 777 ./public/storage
else
	chmod -R 777 ./public/storage
fi

#@toto toto je tu len docasne!
rm -rf ./log/*

#cd ../../bin/php/php5.3.8/
#php.exe -f "C:/wamp/www/trax/public/index.php" orm:generate-proxies
#php.exe -f "C:/wamp/www/trax/public/index.php" orm:schema-tool:create