#!/bin/bash

if [ ! -d ./temp ]; then
	mkdir -m 777 ./temp
else
	chmod 777 ./temp
	rm -rf ./temp/*
fi

if [ ! -d ./temp/sessions ]; then
	mkdir -m 777 ./temp/sessions
else
	chmod 777 ./temp/sessions
fi

if [ ! -d ./temp/proxies ]; then
	mkdir -m 777 ./temp/proxies
else
	chmod 777 ./temp/proxies
fi

if [ ! -d ./temp/presenters ]; then
	mkdir -m 777 ./temp/presenters
else
	chmod 777 ./temp/presenters
fi

if [ ! -d ./log ]; then
	mkdir -m 777 ./log
else
	chmod 777 ./log
fi

if [ ! -d ./public/webtemp ]; then
	mkdir -m 777 ./public/webtemp
else
	chmod 777 ./public/webtemp
	rm -rf ./public/webtemp/*
fi

if [ ! -d ./app/locale ]; then
	mkdir -m 777 ./app/locale
else
	chmod -R 777 ./app/locale
fi

if [ ! -d ./public/storage ]; then
	mkdir -m 777 ./public/storage
else
	chmod -R 777 ./public/storage
fi

#@toto toto je tu len docasne!
rm -rf ./log/*

cd public
php -f index.php orm:generate-proxies
#php public/index.php orm:schema-tool:create
#php public/index.php orm:schema-tool:update --dump-sql
# php public/index.php orm:schema-tool:update --force

#run test
#sh run-tests.sh -p /Applications/MAMP/bin/php/php5.3.6/bin/php
#/usr/local/mysql/bin/mysqldump -h 127.0.0.1 -u root -proot tralandia | /usr/local/mysql/bin/mysql -h 127.0.0.1 -u root -proot tralandia_dump
#/usr/local/mysql/bin/mysqldump -h 127.0.0.1 -u root -proot tralandia_dump | /usr/local/mysql/bin/mysql -h 127.0.0.1 -u root -proot tralandia_test
#/usr/local/mysql/bin/mysqldump -h 127.0.0.1 -u root -proot tralandia | /usr/local/mysql/bin/mysql -h 127.0.0.1 -u root -proot tralandia_test
