<?php
/**
 * This file is part of the tralandia.
 * User: macbook
 * Created at: 25/11/13 09:56
 */

namespace AdminModule;


use Nette;

class ImportCurrenciesPresenter extends BasePresenter
{

	public function actionExecute()
	{
		/** @var $currencyDao \Tralandia\BaseDao */
		$currencyDao = $this->em->getRepository(CURRENCY_ENTITY);

		$data = $this->data;

		$finalData = [];
		foreach($data as $currencyData) {
			list($countryName, $currencyName, $currencyIso) = $currencyData;
			if($currencyIso == 'None') continue;
			$currencyIso = str_replace('[N]', '', $currencyIso);
			$finalData[$currencyIso] = $currencyName;
		}

		$i = 0;
		foreach($finalData as $currencyIso => $currencyName) {
			$entity = $currencyDao->findBy(['iso' => $currencyIso]);
			if($entity) continue;

			/** @var $entity \Entity\Currency */
			$entity = $currencyDao->createNew();
			$entity->setIso($currencyIso);
			$entity->getName()->getCentralTranslation()->setTranslation($currencyName);

			$currencyDao->getEntityManager()->persist($entity);

			//if($i == 10) break;
			$i++;
		}

		$currencyDao->getEntityManager()->flush();
	}



	public $data = [
		["United Arab Emirates", "United Arab Emirates dirham", "AED"],
		["Afghanistan", "Afghan afghani", "AFN"],
		["Albania", "Albanian lek", "ALL"],
		["Armenia", "Armenian dram", "AMD"],
		["Nagorno-Karabakh Republic", "Armenian dram", "AMD"],
		["Curaçao", "Netherlands Antillean guilder", "ANG"],
		["Sint Maarten", "Netherlands Antillean guilder", "ANG"],
		["Angola", "Angolan kwanza", "AOA"],
		["Argentina", "Argentine peso", "ARS"],
		["Australia", "Australian dollar", "AUD"],
		["Cocos (Keeling) Islands", "Australian dollar", "AUD"],
		["Kiribati", "Australian dollar", "AUD"],
		["Nauru", "Australian dollar", "AUD"],
		["Tuvalu", "Australian dollar", "AUD"],
		["Aruba", "Aruban florin", "AWG"],
		["Azerbaijan", "Azerbaijani manat", "AZN"],
		["Bosnia and Herzegovina", "Bosnia and Herzegovina convertible mark", "BAM"],
		["Barbados", "Barbadian dollar", "BBD"],
		["Bangladesh", "Bangladeshi taka", "BDT"],
		["Bulgaria", "Bulgarian lev", "BGN"],
		["Bahrain", "Bahraini dinar", "BHD"],
		["Burundi", "Burundian franc", "BIF"],
		["Bermuda", "Bermudian dollar", "BMD"],
		["Brunei", "Brunei dollar", "BND"],
		["Singapore", "Brunei dollar", "BND"],
		["Bolivia", "Bolivian boliviano", "BOB"],
		["Brazil", "Brazilian real", "BRL"],
		["Bahamas, The", "Bahamian dollar", "BSD"],
		["Bhutan", "Bhutanese ngultrum", "BTN"],
		["Botswana", "Botswana pula", "BWP"],
		["Zimbabwe", "Botswana pula", "BWP"],
		["Belarus", "Belarusian ruble", "BYR"],
		["Belize", "Belize dollar", "BZD"],
		["Canada", "Canadian dollar", "CAD"],
		["Congo, Democratic Republic of the", "Congolese franc", "CDF"],
		["Liechtenstein", "Swiss franc", "CHF"],
		["Switzerland", "Swiss franc", "CHF"],
		["Chile", "Chilean peso", "CLP"],
		["China, People's Republic of", "Chinese yuan", "CNY"],
		["Colombia", "Colombian peso", "COP"],
		["Costa Rica", "Costa Rican colón", "CRC"],
		["Cuba", "Cuban convertible peso", "CUC"],
		["Cuba", "Cuban peso", "CUP"],
		["Cape Verde", "Cape Verdean escudo", "CVE"],
		["Czech Republic", "Czech koruna", "CZK"],
		["Djibouti", "Djiboutian franc", "DJF"],
		["Denmark", "Danish krone", "DKK"],
		["Faroe Islands", "Danish krone", "DKK"],
		["Dominican Republic", "Dominican peso", "DOP"],
		["Algeria", "Algerian dinar", "DZD"],
		["Sahrawi Republic", "Algerian dinar", "DZD"],
		["Egypt", "Egyptian pound", "EGP"],
		["Eritrea", "Eritrean nakfa", "ERN"],
		["Ethiopia", "Ethiopian birr", "ETB"],
		["Akrotiri and Dhekelia", "Euro", "EUR"],
		["Andorra", "Euro", "EUR"],
		["Austria", "Euro", "EUR"],
		["Belgium", "Euro", "EUR"],
		["Cyprus", "Euro", "EUR"],
		["Estonia", "Euro", "EUR"],
		["Finland", "Euro", "EUR"],
		["France", "Euro", "EUR"],
		["Germany", "Euro", "EUR"],
		["Greece", "Euro", "EUR"],
		["Ireland", "Euro", "EUR"],
		["Italy", "Euro", "EUR"],
		["Kosovo", "Euro", "EUR"],
		["Luxembourg", "Euro", "EUR"],
		["Malta", "Euro", "EUR"],
		["Monaco", "Euro", "EUR"],
		["Montenegro", "Euro", "EUR"],
		["Netherlands", "Euro[I]", "EUR"],
		["Portugal", "Euro", "EUR"],
		["San Marino", "Euro", "EUR"],
		["Slovakia", "Euro", "EUR"],
		["Slovenia", "Euro", "EUR"],
		["Spain", "Euro", "EUR"],
		["Vatican City", "Euro", "EUR"],
		["Zimbabwe", "Euro", "EUR"],
		["Fiji", "Fijian dollar", "FJD"],
		["Falkland Islands", "Falkland Islands pound", "FKP"],
		["Alderney", "British pound[C]", "GBP"],
		["Guernsey", "British pound[C]", "GBP"],
		["Isle of Man", "British pound[C]", "GBP"],
		["Jersey", "British pound[C]", "GBP"],
		["South Georgia and the South Sandwich Islands", "British pound", "GBP"],
		["United Kingdom", "British pound[C]", "GBP"],
		["Zimbabwe", "British pound[C]", "GBP"],
		["Georgia", "Georgian lari", "GEL"],
		["Alderney", "Guernsey pound", "GGP[N]"],
		["Ghana", "Ghana cedi", "GHS"],
		["Gibraltar", "Gibraltar pound", "GIP"],
		["Gambia, The", "Gambian dalasi", "GMD"],
		["Guinea", "Guinean franc", "GNF"],
		["Guatemala", "Guatemalan quetzal", "GTQ"],
		["Guyana", "Guyanese dollar", "GYD"],
		["Hong Kong", "Hong Kong dollar", "HKD"],
		["Honduras", "Honduran lempira", "HNL"],
		["Croatia", "Croatian kuna", "HRK"],
		["Haiti", "Haitian gourde", "HTG"],
		["Hungary", "Hungarian forint", "HUF"],
		["Indonesia", "Indonesian rupiah", "IDR"],
		["Israel", "Israeli new shekel", "ILS"],
		["Palestine", "Israeli new shekel", "ILS"],
		["Isle of Man", "Manx pound", "IMP[N]"],
		["Bhutan", "Indian rupee", "INR"],
		["India", "Indian rupee", "INR"],
		["Iraq", "Iraqi dinar", "IQD"],
		["Iran", "Iranian rial", "IRR"],
		["Iceland", "Icelandic króna", "ISK"],
		["Jersey", "Jersey pound", "JEP[N]"],
		["Jamaica", "Jamaican dollar", "JMD"],
		["Jordan", "Jordanian dinar", "JOD"],
		["Palestine", "Jordanian dinar", "JOD"],
		["Japan", "Japanese yen", "JPY"],
		["Kenya", "Kenyan shilling", "KES"],
		["Kyrgyzstan", "Kyrgyzstani som", "KGS"],
		["Cambodia", "Cambodian riel", "KHR"],
		["Comoros", "Comorian franc", "KMF"],
		["Korea, North", "North Korean won", "KPW"],
		["Korea, South", "South Korean won", "KRW"],
		["Kuwait", "Kuwaiti dinar", "KWD"],
		["Cayman Islands", "Cayman Islands dollar", "KYD"],
		["Kazakhstan", "Kazakhstani tenge", "KZT"],
		["Laos", "Lao kip", "LAK"],
		["Lebanon", "Lebanese pound", "LBP"],
		["Sri Lanka", "Sri Lankan rupee", "LKR"],
		["Liberia", "Liberian dollar", "LRD"],
		["Lesotho", "Lesotho loti", "LSL"],
		["Lithuania", "Lithuanian litas", "LTL"],
		["Latvia", "Latvian lats", "LVL"],
		["Libya", "Libyan dinar", "LYD"],
		["Morocco", "Moroccan dirham", "MAD"],
		["Sahrawi Republic", "Moroccan dirham", "MAD"],
		["Moldova", "Moldovan leu", "MDL"],
		["Madagascar", "Malagasy ariary", "MGA"],
		["Macedonia, Republic of", "Macedonian denar", "MKD"],
		["Burma", "Burmese kyat", "MMK"],
		["Mongolia", "Mongolian tögrög", "MNT"],
		["Macau", "Macanese pataca", "MOP"],
		["Mauritania", "Mauritanian ouguiya", "MRO"],
		["Sahrawi Republic", "Mauritanian ouguiya", "MRO"],
		["Mauritius", "Mauritian rupee", "MUR"],
		["Maldives", "Maldivian rufiyaa", "MVR"],
		["Malawi", "Malawian kwacha", "MWK"],
		["Mexico", "Mexican peso", "MXN"],
		["Malaysia", "Malaysian ringgit", "MYR"],
		["Mozambique", "Mozambican metical", "MZN"],
		["Namibia", "Namibian dollar", "NAD"],
		["Nigeria", "Nigerian naira", "NGN"],
		["Nicaragua", "Nicaraguan córdoba", "NIO"],
		["Norway", "Norwegian krone", "NOK"],
		["Abkhazia", "Abkhazian apsar[A]", "None"],
		["Alderney", "Alderney pound[A]", "None"],
		["United Kingdom Ascension Island", "Ascension pound[A]", "None"],
		["British Virgin Islands", "British Virgin Islands dollar[A]", "None"],
		["Cook Islands", "Cook Islands dollar", "None"],
		["East Timor", "None", "None"],
		["Ecuador", "None", "None"],
		["Faroe Islands", "Faroese króna", "None"],
		["Guernsey", "Guernsey pound", "None"],
		["Kiribati", "Kiribati dollar[A]", "None"],
		["Micronesia", "Micronesian dollar[A]", "None"],
		["Nagorno-Karabakh Republic", "Nagorno-Karabakh dram[A]", "None"],
		["Nauru", "Nauruan dollar[A]", "None"],
		["Niue", "Niuean dollar[A]", "None"],
		["Palau", "Palauan dollar[A]", "None"],
		["Pitcairn Islands", "Pitcairn Islands dollar[A]", "None"],
		["Sahrawi Republic", "Sahrawi peseta[J]", "None"],
		["Somaliland", "Somaliland shilling", "None"],
		["South Georgia and the South Sandwich Islands", "South Georgia and the South Sandwich Islands pound[A]", "None"],
		["Tristan da Cunha", "Tristan da Cunha pound[A]", "None"],
		["Tuvalu", "Tuvaluan dollar", "None"],
		["Nepal", "Nepalese rupee", "NPR"],
		["Cook Islands", "New Zealand dollar", "NZD"],
		["New Zealand", "New Zealand dollar", "NZD"],
		["Niue", "New Zealand dollar", "NZD"],
		["Pitcairn Islands", "New Zealand dollar", "NZD"],
		["Oman", "Omani rial", "OMR"],
		["Panama", "Panamanian balboa", "PAB"],
		["Peru", "Peruvian nuevo sol", "PEN"],
		["Papua New Guinea", "Papua New Guinean kina", "PGK"],
		["Philippines", "Philippine peso", "PHP"],
		["Pakistan", "Pakistani rupee", "PKR"],
		["Poland", "Polish złoty", "PLN"],
		["Transnistria", "Transnistrian ruble", "PRB[N]"],
		["Paraguay", "Paraguayan guaraní", "PYG"],
		["Qatar", "Qatari riyal", "QAR"],
		["Romania", "Romanian leu", "RON"],
		["Serbia", "Serbian dinar", "RSD"],
		["Abkhazia", "Russian ruble", "RUB"],
		["Russia", "Russian ruble", "RUB"],
		["South Ossetia", "Russian ruble", "RUB"],
		["Rwanda", "Rwandan franc", "RWF"],
		["Saudi Arabia", "Saudi riyal", "SAR"],
		["Solomon Islands", "Solomon Islands dollar", "SBD"],
		["Seychelles", "Seychellois rupee", "SCR"],
		["Sudan", "Sudanese pound", "SDG"],
		["Sweden", "Swedish krona", "SEK"],
		["Brunei", "Singapore dollar", "SGD"],
		["Singapore", "Singapore dollar", "SGD"],
		["United Kingdom Ascension Island", "Saint Helena pound", "SHP"],
		["Saint Helena", "Saint Helena pound", "SHP"],
		["Tristan da Cunha", "Saint Helena pound", "SHP"],
		["Sierra Leone", "Sierra Leonean leone", "SLL"],
		["Somalia", "Somali shilling", "SOS"],
		["Suriname", "Surinamese dollar", "SRD"],
		["South Sudan", "South Sudanese pound", "SSP"],
		["São Tomé and Príncipe", "São Tomé and Príncipe dobra", "STD"],
		["Syria", "Syrian pound", "SYP"],
		["Swaziland", "Swazi lilangeni", "SZL"],
		["Thailand", "Thai baht", "THB"],
		["Tajikistan", "Tajikistani somoni", "TJS"],
		["Turkmenistan", "Turkmenistan manat", "TMT"],
		["Tunisia", "Tunisian dinar", "TND"],
		["Tonga", "Tongan paʻanga", "TOP"],
		["Northern Cyprus", "Turkish lira", "TRY"],
		["Turkey", "Turkish lira", "TRY"],
		["Trinidad and Tobago", "Trinidad and Tobago dollar", "TTD"],
		["Taiwan", "New Taiwan dollar", "TWD"],
		["Tanzania", "Tanzanian shilling", "TZS"],
		["Ukraine", "Ukrainian hryvnia", "UAH"],
		["Uganda", "Ugandan shilling", "UGX"],
		["Bonaire", "United States dollar", "USD"],
		["British Indian Ocean Territory", "United States dollar", "USD"],
		["British Virgin Islands", "United States dollar", "USD"],
		["East Timor", "United States dollar", "USD"],
		["Ecuador", "United States dollar", "USD"],
		["El Salvador", "United States dollar", "USD"],
		["Marshall Islands", "United States dollar", "USD"],
		["Micronesia", "United States dollar", "USD"],
		["Palau", "United States dollar", "USD"],
		["Panama", "United States dollar", "USD"],
		["Saba", "United States dollar", "USD"],
		["Sint Eustatius", "United States dollar", "USD"],
		["Turks and Caicos Islands", "United States dollar", "USD"],
		["United States", "United States dollar", "USD"],
		["Zimbabwe", "United States dollar", "USD"],
		["Uruguay", "Uruguayan peso", "UYU"],
		["Uzbekistan", "Uzbekistani som", "UZS"],
		["Venezuela", "Venezuelan bolívar", "VEF"],
		["Vietnam", "Vietnamese đồng", "VND"],
		["Vanuatu", "Vanuatu vatu", "VUV"],
		["Samoa", "Samoan tālā", "WST"],
		["Cameroon", "Central African CFA franc", "XAF"],
		["Central African Republic", "Central African CFA franc", "XAF"],
		["Chad", "Central African CFA franc", "XAF"],
		["Congo, Republic of the", "Central African CFA franc", "XAF"],
		["Equatorial Guinea", "Central African CFA franc", "XAF"],
		["Gabon", "Central African CFA franc", "XAF"],
		["Anguilla", "East Caribbean dollar", "XCD"],
		["Antigua and Barbuda", "East Caribbean dollar", "XCD"],
		["Dominica", "East Caribbean dollar", "XCD"],
		["Grenada", "East Caribbean dollar", "XCD"],
		["Montserrat", "East Caribbean dollar", "XCD"],
		["Saint Kitts and Nevis", "East Caribbean dollar", "XCD"],
		["Saint Lucia", "East Caribbean dollar", "XCD"],
		["Saint Vincent and the Grenadines", "East Caribbean dollar", "XCD"],
		["Benin", "West African CFA franc", "XOF"],
		["Burkina Faso", "West African CFA franc", "XOF"],
		["Côte d'Ivoire", "West African CFA franc", "XOF"],
		["Guinea-Bissau", "West African CFA franc", "XOF"],
		["Mali", "West African CFA franc", "XOF"],
		["Niger", "West African CFA franc", "XOF"],
		["Senegal", "West African CFA franc", "XOF"],
		["Togo", "West African CFA franc", "XOF"],
		["French Polynesia", "CFP franc", "XPF"],
		["New Caledonia", "CFP franc", "XPF"],
		["Wallis and Futuna", "CFP franc", "XPF"],
		["Yemen", "Yemeni rial", "YER"],
		["Lesotho", "South African rand", "ZAR"],
		["Namibia", "South African rand", "ZAR"],
		["South Africa", "South African rand", "ZAR"],
		["Zimbabwe", "South African rand", "ZAR"],
		["Zambia", "Zambian kwacha", "ZMW"],
	];

}
