<?php
/**
 * @license LGPL
 */

    $grid = $control;
    $editovatelnePolicka = $grid->editableFields;

    $sloupecky = array();
    $i=0;
    foreach($grid->getComponents(false, '\DataGrid\Columns\IColumn') AS $dgColName => $dgColumn) {
		// pridanie classy
		$dgColumn->getCellPrototype()->addClass('editable');

        $sloupecek = $sloupecky[$i] = (object)null;
        $sloupecek->editable = false;
        if(isset($editovatelnePolicka[$dgColName])) {
            $column = $editovatelnePolicka[$dgColName];
            $sloupecek->editable = true;
            $sloupecek->type = $column->type;
            $sloupecek->name = $column->columnName;

            // Dictionary is used for example in selects. (in datagrid is translated value, but in database we have only ID)
            $dict = $sloupecek->dictionary = (object)null;
            $dict->keys = array();
            $dict->values = array();
            foreach($column->dictionary AS $key => $val){
                $dict->keys[] = $key;
                $dict->values[] = $val;
            }
            $sloupecek->formControl = $column->__toString();
        }
        $i++;
    }

    $sloupecky_json = \Nette\Utils\Json::encode($sloupecky);
?>
{if !$presenter->isAjax()}
<style type="text/css">
    .ui-effects-transfer { border: 2px dotted gray; } 
</style>
<script type="text/JavaScript" src="{$basePath}/scripts/jquery/editable.js"></script>
<script type="text/JavaScript" src="{$basePath}/scripts/sha1.js"></script>
<script type="text/JavaScript" src="{$basePath}/scripts/rawurlencode.js"></script>
<script type="text/JavaScript" src="{$basePath}/scripts/utf8_encode.js"></script>
{/if}
<script type="text/JavaScript" n:syntax="double">

	/**
	 * Getts column value
	 */
	var getColumnValue = function(column) {
	    if(column.is("div")) {
	        return column.text();
	    }else{
	        return column.attr("value");
	    }
	}

	/**
	 * Setts column value
	 */
	var setColumnValue = function(column,value){
	    if(column.is("div")) {
	        column.text(value);
	    }else{
	        column.attr("value",value);
	    }
	}

	$("table.datagrid tbody tr").click(function() {
		var ok = $('<a href="#">ok</a>');
		var nok = $('<a href="#">x</a>');
		$("table.datagrid tbody tr td.editableActions").remove();
		$(this).append($('<td class="editableActions"></td>').append(nok).append('&nbsp;').append(ok));
		
		ok.click(function(e) {
			e.preventDefault();
			var ajaxData = {}, rowID = 0, button = $(this), tr = button.parents("tr");
			tr.find("td").each(function() {
				var data = $(this).data('editableGrid');
				if (!rowID) {
					rowID = $(this).data('rowID');
				}
				if (data && data.editable === true) {
					ajaxData[data.name] = getColumnValue($(this).find("(input,select,div[contenteditable]):first"));
				}
			});
			
			var link = {{link saveColumnData! dataGrid => $grid->getUniqueId()}};
			$.post(link, {"{{!$grid->getUniqueId()}}-cisloRadku": rowID, "{{!$grid->getUniqueId()}}-data": JSON.stringify(ajaxData)}, function(payload) {
				if (payload.editableDatagrid.success != true) {
					tr.find("td").each(function() {
						var origValue = $(this).data('origValue');
						setColumnValue($(this).find("(input,select,div[contenteditable]):first"), origValue);
					});
				}
				$.nette.success(payload);
				$("table.datagrid tbody tr td.editableActions").remove();
			}, "json");
		});
		
		nok.click(function(e) {
			e.preventDefault();
			var button = $(this), tr = button.parents("tr");
			tr.find("td").each(function() {
				var origValue = $(this).data('origValue');debug(origValue);
				setColumnValue($(this).find("(input,select,div[contenteditable]):first"), origValue);
			});
			$("table.datagrid tbody tr td.editableActions").remove();
		});
	});
	
    $("table.datagrid tbody tr td:not(.checker,.actions,.editableActions)").each(function(){
        var sloupecky = {{!$sloupecky_json}};
        var t = $(this);
        var cisloSloupecku = t.parent().find("td:not(.checker)").index(t);
        var infoSloupecku = sloupecky[cisloSloupecku];
        var idRadku = t.parent().attr("id").split("___");
        idRadku = idRadku[idRadku.length-1];
			
		t.data({
			editableGrid: infoSloupecku,
			rowID: idRadku
		});

        if(infoSloupecku.editable === true){
            if(infoSloupecku.type == "TEXT" || infoSloupecku.type == "TEXTAREA"){
                t.wrapInner("<div></div>").find("div").editable();
            }else{
                var value = t.text();
                t.html("");
                var input = $(infoSloupecku.formControl);
                if(infoSloupecku.dictionary.values.length>0){
                    // Použijem překladový slovník
                    var keyValue = infoSloupecku.dictionary.values.search(value);
                    var keyValue = infoSloupecku.dictionary.keys[keyValue];
                    input.attr("value",keyValue);
                }else{
                    input.attr("value",value);
                }
                input.appendTo(t);
            }
            
            var input = $("(input,select,div[contenteditable]):first",t);

            input.focus(function() {
                var t = $(this);
                t.parent().data("origValue", getColumnValue(t));
            });
        }
    });
</script>