<?php

use Routers\FrontRoute;

return [
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 28, FrontRoute::LOCATION => 1246, FrontRoute::RENTAL_TYPE => 1],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 66, FrontRoute::LOCATION => 1247, FrontRoute::RENTAL_TYPE => 2],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 135, FrontRoute::LOCATION => 1248, FrontRoute::RENTAL_TYPE => 3],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 100, FrontRoute::LOCATION => 1249, FrontRoute::RENTAL_TYPE => 4],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 154, FrontRoute::LOCATION => 1250, FrontRoute::RENTAL_TYPE => 5],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 145, FrontRoute::LOCATION => 1251, FrontRoute::RENTAL_TYPE => 6],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 129, FrontRoute::LOCATION => 1252, FrontRoute::RENTAL_TYPE => 7],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 58, FrontRoute::LOCATION => 1253, FrontRoute::RENTAL_TYPE => 8],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 150, FrontRoute::LOCATION => 1254, FrontRoute::RENTAL_TYPE => 9],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 41, FrontRoute::LOCATION => 1255, FrontRoute::RENTAL_TYPE => 10],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 40, FrontRoute::LOCATION => 1256, FrontRoute::RENTAL_TYPE => 11],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 60, FrontRoute::LOCATION => 1257, FrontRoute::RENTAL_TYPE => 12],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 183, FrontRoute::LOCATION => 1258, FrontRoute::RENTAL_TYPE => 13],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 45, FrontRoute::LOCATION => 10117, FrontRoute::RENTAL_TYPE => 14],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 15, FrontRoute::LOCATION => 10118, FrontRoute::RENTAL_TYPE => 1],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 33, FrontRoute::LOCATION => 10119, FrontRoute::RENTAL_TYPE => 2],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 73, FrontRoute::LOCATION => 10120, FrontRoute::RENTAL_TYPE => 3],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 159, FrontRoute::LOCATION => 10121, FrontRoute::RENTAL_TYPE => 4],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 175, FrontRoute::LOCATION => 10122, FrontRoute::RENTAL_TYPE => 5],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 37, FrontRoute::LOCATION => 10123, FrontRoute::RENTAL_TYPE => 6],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 136, FrontRoute::LOCATION => 10124, FrontRoute::RENTAL_TYPE => 7],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 62, FrontRoute::LOCATION => 10125, FrontRoute::RENTAL_TYPE => 8],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 23, FrontRoute::LOCATION => 10126, FrontRoute::RENTAL_TYPE => 9],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 75, FrontRoute::LOCATION => 10127, FrontRoute::RENTAL_TYPE => 10],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 48, FrontRoute::LOCATION => 10128, FrontRoute::RENTAL_TYPE => 11],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 98, FrontRoute::LOCATION => 10129, FrontRoute::RENTAL_TYPE => 12],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 108, FrontRoute::LOCATION => 10130, FrontRoute::RENTAL_TYPE => 13],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 32, FrontRoute::LOCATION => 10131, FrontRoute::RENTAL_TYPE => 14],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 131, FrontRoute::LOCATION => 10132, FrontRoute::RENTAL_TYPE => 1],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 116, FrontRoute::LOCATION => 10133, FrontRoute::RENTAL_TYPE => 2],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 171, FrontRoute::LOCATION => 10134, FrontRoute::RENTAL_TYPE => 3],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 118, FrontRoute::LOCATION => 10135, FrontRoute::RENTAL_TYPE => 4],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 38, FrontRoute::LOCATION => 10136, FrontRoute::RENTAL_TYPE => 5],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 144, FrontRoute::LOCATION => 10137, FrontRoute::RENTAL_TYPE => 6],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 162, FrontRoute::LOCATION => 10138, FrontRoute::RENTAL_TYPE => 7],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 165, FrontRoute::LOCATION => 10139, FrontRoute::RENTAL_TYPE => 8],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 28, FrontRoute::LOCATION => 10140, FrontRoute::RENTAL_TYPE => 9],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 66, FrontRoute::LOCATION => 10141, FrontRoute::RENTAL_TYPE => 10],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 135, FrontRoute::LOCATION => 10142, FrontRoute::RENTAL_TYPE => 11],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 100, FrontRoute::LOCATION => 10143, FrontRoute::RENTAL_TYPE => 12],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 154, FrontRoute::LOCATION => 10144, FrontRoute::RENTAL_TYPE => 13],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 145, FrontRoute::LOCATION => 10145, FrontRoute::RENTAL_TYPE => 14],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 129, FrontRoute::LOCATION => 10146, FrontRoute::RENTAL_TYPE => 1],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 58, FrontRoute::LOCATION => 10147, FrontRoute::RENTAL_TYPE => 2],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 150, FrontRoute::LOCATION => 10148, FrontRoute::RENTAL_TYPE => 3],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 41, FrontRoute::LOCATION => 10149, FrontRoute::RENTAL_TYPE => 4],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 40, FrontRoute::LOCATION => 10150, FrontRoute::RENTAL_TYPE => 5],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 60, FrontRoute::LOCATION => 10151, FrontRoute::RENTAL_TYPE => 6],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 183, FrontRoute::LOCATION => 10152, FrontRoute::RENTAL_TYPE => 7],
	['presenter' => 'RentalList', 'action' => 'default', FrontRoute::PRIMARY_LOCATION => 52, FrontRoute::LANGUAGE => 45, FrontRoute::LOCATION => 10153, FrontRoute::RENTAL_TYPE => 8],
];
